### ISSUE TITLE
[Week8] 인터페이스

### ISSUE THREAD

**Issue by pbg0205** [codesquad-study/java#10]
https://github.com/whiteship/live-study/issues/8

**Comment by janeljs** [comment]
### 추상 클래스와 인터페이스의 의미 (출처 쿠퍼)

- 추상(abstract) : `is-a` 관계
  - 클래스 계층구조에서 `안정성` 제공
  - 클래스의 상속 관계에서 결합도가 높다.
  - 부모 클래스의 명세 변경 시, 코드 손상될 우려가 있다.

<br>

- 인터페이스(interface) : `has-a` 관계

  - 생성된 클래스 간 결합도가 낮다.

  - 상속에 비해 명세 변경시, 구성 요소를 쉽게 변경할 수 있다.(유연성 제공)

    

- ex) Cooper는 Person(사람)이면서 개발할 수 있다.(Developable)

  ```java
  class Cooper extends Person implements Developable {}
  ```
💡 인터페이스와 추상 클래스의 결합도 차이에 대해 알아보자.

**Comment by janeljs** [comment]
기본 메소드가 있는 인터페이스를 상속받은 인터페이스에서 다시 추상 메소드로 변경할 수 있다.

**Comment by janeljs** [comment]
인터페이스에서 사용할 수 있는 접근제어자

**Comment by janeljs** [comment]
### 익명 구현 객체 사용

인터페이스는 원칙적으로는 객체화 될 순 없지만, 익명 객체를 통해서 인터페이스를 구현하는 일회용 객체를 만들 수 있다.
```java
Fightable fight = new Fightable() {
      @Override
      public void void() {
          System.out.println("moving");
      }
  };
```
익명 객체를 활용하여 인터페이스 자체만으로 구현할 수 있다.

이렇게 쓰는 경우 익명 객체를 만들어 변수 fight에 주입시켜 준다.
  - java의 인터페이스에는 생성자가 없으므로, 항상 Fightable()의 괄호는 빈 상태
  - 단순히 인터페이스의 구현역할을 하는 익명객체일뿐, 상속이나 또다른 인터페이스를 구현하는 것은 불가능하다.
  - 또한, 이것은 expresison의 일종이므로 뒤에 세미콜론을 붙여야 한다.

응용버전
```java
List<Runnable> actions = new ArrayList<Runnable>();
actions.add(new Runnable() {
    @Override
    public void run() {
        ...
    }
});
```
https://dncjf64.tistory.com/262?category=757101

**Comment by sanhee** [comment]
# 오늘 키워드

1. 강한결합, 내부결합
2. ISP, OCP
3. GitHub 이미지
 - ./img/~ 절대경로
4. 인터페이스의 다중상속이 불가능 한 경우
5. Which should you use, abstract classes or interfaces?
6. 기본 메서드가 나온 배경 (쿠퍼)
 - 이전은 추상 클래스
7. 기본 메소드가 있는 인터페이스를 상속받은 인터페이스에서 다시 추상 메소드로 변경할 수 있다.
