### ISSUE TITLE
[Week9] 예외 처리

### ISSUE THREAD

**Issue by jihye-woo** [codesquad-study/java#12]
https://github.com/whiteship/live-study/issues/9

**Comment by janeljs** [comment]
https://velog.io/@janeljs/codesquad-tech-talk-1

**Comment by sanhee** [comment]
# exception과 error

- 개발자가 케어할 수 있는지?

----

# catch (e1) { ... }

- 적절한 catch블럭을 찾지 못하면 예외 처리 불가 -> 프로그램 강제 종료
- 적절한 catch블럭을 찾으면 throw 문의 피연산자를 예외 객체의 형식 매개변수로 전달

----

# 멀티 catch

![](https://images.velog.io/images/san/post/51e9b720-3a11-446a-be7c-0dbd12183a12/image.png)

![](https://images.velog.io/images/san/post/413a6bdf-972c-43ee-a1e6-5d1d5552a8fe/image.png)

![](https://images.velog.io/images/san/post/b1032876-85ab-4e66-9ca4-0181fcbf674b/image.png)

![](https://images.velog.io/images/san/post/d680e507-5e76-4d4c-ad3e-9ca026973ef9/image.png)


----

# try-catch-resources

- Effectively Final
  - https://www.baeldung.com/java-effectively-final#
- AutoCloseable

----

# Runtime Exception이 예외를 명세하지 않는 이유?

- Runtime Exception은 프로그램 코드의 문제로 발생하는 예외이다.
- 클라이언트 쪽(메서드 호출하는 쪽)에서 이를 복구(or 회복)하거나 대처할 수 있을 거라고 예상하기 힘들다.
- RuntimeException은 프로그램 어디서나 매우 빈번하게 발생할 수 있기 때문에 모든 Runtime Exception을 메서드에 명시하도록 강제하는 것은 프로그램의 명확성을 떨어뜨릴 수 있다.


---

# RuntimeException 클래스와 그 자손들
 - 프로그래머의 실수로 발생하는 예외
 - e.g. ClassCastException
 - try/catch문을 사용하기보다는 예외에 신경쓰며 프로그램 작성하기
 
 
---

# 예외 처리 일반적인 방법 3가지
   - 그림설명: https://www.notion.so/3565a9689f714638af34125cbb8abbe8
   <br>
   - 예외 복구
     - 다른 작업 흐름으로 유도
     - 예외가 발생해도 애플리케이션은 정상 흐름으로 진행
     - ex) 네트워크 딜레이
   - 예외처리 회피
     - 처리하지 않고 호출한 쪽으로 예외 전달
     - ex) throws
   - 예외전환
     - 명확한 의미의 예외로 전환 후 예외 전달
     - ex) checked exception -> uncehcked excpetion전환
---

# [5] User-defined Custom Exception

1. 사용자 정의 예외 작성법

   - User-defined exception을 작성하기 위해서는 Exception을 상속받아 exception class를 구현한다.
   - 사용자 정의 예외 클래스 작성 시, 생성자에 문자열을 추가하고 super 클래스에 추가하면 getMessage()를 통해 예외 메세지를 확인할 수 있다.

2. 사용자 정의 예외의 장점

   - 이름으로도 정보 전달이 가능하다.🥕 쿠퍼가 느끼는 장점
   - 상세한 예외 정보를 제공할 수 있다. 🥕 쿠퍼가 느끼는 장점
   - 예외에 대한 응집도가 향상된다.
   - 예외 발생 후, 후처리가 용이하다.
   - 예외 생성 비용을 감소시킨다.

   출처 : [custom exception을 언제 써야 할까?](https://woowacourse.github.io/javable/post/2020-08-17-custom-exception/)
   
   
---

# 커스텀 예외

- Throwable cause

![](https://images.velog.io/images/san/post/86a58d22-4a08-4ee9-ac97-4c70bdd3c9a1/image.png)

- https://github.com/codesquad-study/java/blob/main/Week9/jane/WEEK9.md

----
1. Re-throwing Exceptions
2. Wrapping Exceptions
- 말 그대로 예외를 래핑해서 상위로 전달할 수 있다.
- 좀 더 추상화 수준이 높은 예외로 랩핑해서 던질 수 있다는 장점
- 복구가 불가능한 Checked Exception을 처리해야할 경우, 이를 Unchecked Exception으로 - 전환하여 다른 계층에서 일일이 예외를 선언할 필요가 없도록 할 수도 있다.
- https://github.com/codesquad-study/java/tree/main/Week9/woody


----

#### (+) 이펙티브 자바에서 예외 언급
 - https://github.com/codesquad-study/java/edit/main/Week9/woody

- **아이템 69. 예외는 진짜 예외 상황에만 사용하라**
  - 예외는 반드시 예외 상황에서만 사용하며 일상적인 제어 흐름용으로 사용해서는 안 된다
  - 예외가 발생하기 전, 상태 검사 메서드를 제공하거나 옵셔널 또는 특정 값을 반환하도록 하는 등 미리 프로그램의 흐름을 적절하게 제어하는 것이 좋다.
  - 예를 들어, Iterable 인터페이스를 사용하기 위해서 상태 검사 메소드인 hasNext를 사용해서 정상적인 제어 흐름에 대한 처리를 해주는 것이 중요하다.

- **아이템 70. 복구할 수 있는 상황에는 검사 예외를, 프로그래밍 오류에는 런타임 예외를 사용하라**

  - 호출하는 쪽에서 복구가 가능하다면 check exception
    - try-catch로 예외를 처리하거나 혹은 throw를 통해 콜스택의 상위 메소드에서 처리하도록 예외를 바깥으로 던지자

  - 프로그래밍 오류는 보통 uncheck exception으로 처리한다.

- **아이템 71. 필요 없는 검사 예외 사용은 피하라**
  - 과하게 검사 예외를 사용하게 되면 try-catch문이 코드를 뒤덮게 되는 상황이..
  - 가독성 측면에서도 

- **아이템 73. 추상화 수준에 맞는 예외를 던져라**

  - 추상화 수준이 높은 예외로 래핑해서 상위 메소드로 던질 수 있다.

  - ```java
    try {
        // 저수준 추상화를 이용한다.
    } catch (LowerLevelException e) {
        // 추상화 수준에 맞게 다시 랩핑해서 던진다
        throw new HigherLevelException(...);
    }
    ```

# exception 하이레벨 추상화??

![](https://images.velog.io/images/san/post/b10c0914-07eb-4f49-846e-0466c19ef86b/image.png)

- 두부펄처스익셉션 - high
- 엄마노폰 익센션이 - low

https://velog.io/@janeljs/codesquad-tech-talk-1

----

# 예외처리 비용

- 비싸다. 💸💸
- try-catch 블록의 검사로직
- Throwable 생성자의 fillInStackTrace() 메서드 (주원인!)
   - 메모리 영역의 Stack 에 쌓여있는 Stack Frame 들을 pop 하여 출력해주기 때문임.
 - 분기 또는 리턴 로직으로 해결할 수 있는 경우에는 Exception을 사용하지 않는 것이 좋다.
   - 제인: 예외던지는게 더 깔끔한 것 같다?!
   - 패스워드 불일치는 예외처리?
