### ISSUE TITLE
[Week10] 멀티쓰레드 프로그래밍

### ISSUE THREAD

**Issue by jihye-woo** [codesquad-study/java#13]
https://github.com/whiteship/live-study/issues/10

**Comment by sanhee** [comment]
# 스터디 내용

# 스레드, 프로세스
> 스레드 (PC) 가져야 하는 이유.. 아직 잘모르겠음.❓❓❓❓
> 우디: 스레드간 컨텍스트 스위칭을 할 때 작업한 위치를 공유해야해서 필요하다?

>멀티 쓰레드들은 code, data, heap 영역을 공유한다.
code : 실행할 코드를 저장하는 영역
data : 전역변수, 정적변수, 배열, 구조체 등이 저장되는 공간
heap : 사용자(프로그래머)가 직접 관리해야하는 메모리 영역


# Thread vs Runnable
> 상속여부

> - Thread는 class이기 때문에 상속을 받을 수 없다.
- Runnable는 interface이므로 상속이 가능하다.
- Thread를 상속하면 yield(), interrupt()와 같은 inbuilt method를 사용할 수 있다.
- (Runnable interface는 사용이 불가능하다.)
- yield() : 다른 스레드에게 실행을 양보하는 메서드
- interrupt() : 스레드가 일시 정지 상태(sleep) 시, InterruptedException 예외를 발생시킨다.
- (실행 상태에 사용 시, 스레드가 sleep상태가 되면 InterruptedException 발생하며 종료.)
Runnable을 사용시, 여러 thread를 공유할 수 있는 객체를 얻을 수 있다.


# 쓰레드의 상태
![](https://images.velog.io/images/san/post/e438ca5e-c428-4131-8bd8-fe9a19336178/image.png)
>1. New
Thread 객체가 만들어졌지만 아직 시작은 되지 않은 상태
NOT started, NOT runnable
not known to thread scheduler(CPU는 점유하고 있지 않은 상태)
2. Runnable
실행 중 혹은 실행 가능한 상태
Thread 객체가 start() 호출한 뒤의 상태
can be scheduled (CPU 점유권을 얻을 수 있는 상태, 아직 얻진 않음)
3. Running
JVM에 의해 run()이 호출된 상태
scheduled ( CPU를 점유해서 실행중인 상태 )
4. Blocked
Runnable → Unrunnable
스케줄링 될 수 없는 상태
lock 메소드(sleep()과 같이)로 전환
CPU 점유권 상실
cannot be scheduled
5. Dead
run() 메소드를 모두 수행한 뒤의 상태
cannot be rescheduled


# 스레드 이름 설정
```java
Thread thread = new Thread("new-thread-name");
```

# 스레드 우선순위
>- jvm이 기본 우선순위 5로 설정함.
- 쓰레드의 우선순위는 쓰레드를 생성한 쓰레드로부터 상속받음.
- 스레드를 실행하기 전에만 우선순위를 변경할 수 있음. ( run() 되기전 )

# 데몬 스레드(deamon thread)
>일반 스레드들이 종료되면 자동으로 데몬 스레드도 종료.
일반 스레드의 보조 역할을 담당
setDaemon() 으로 데몬 스레드 설정
isDaemon()으로 현재 스레드가 데몬 스레드인지 확인

# 동기화 문제 해결 - synchronized 키워드 활용
>synchronized 키워드는 크게 두 가지 영역에서 사용이 가능하다.

>synchronized 메서드
메서드 전체를 임계 영역으로 설정
메소드 종료 시 쓰레드는 lock을 반환

>synchronized 블럭
락을 걸고자 하는 객체의 참조 값을 synchronized 키워드로 감싼다
블럭 종료 시 쓰레드는 lock을 반환

> 단, 동기화 문제와 오버헤드 가능성에 유의해야 한다.
동기화 문제(Synchronization) : race condition, dead lock
오버헤드 문제 : 스레드 처리 시간보다 스케줄링 시간이 더 소요되는 오버헤드가 발생

# 쓰레드와 공유객체
> 하나의 객체를 여러개의 Thread가 사용한다는 것을 의미.
> 예시 : [프로그래머스] 쓰레드와 공유객체 
> https://programmers.co.kr/learn/courses/9/lessons/273
> synchronized를 메소드에 붙혀서 사용할 경우, 메소드 코드가 길어지면, 마지막에 대기하는 쓰레드가 너무 오래 기다리는 것을 막기 위해 synchorinized를 붙이지 않고, 문제 있을 것 같은 부분만 synchronized 블록을 사용한다.
> https://github.com/codesquad-study/java/tree/main/Week10/cooper

# 동기화 오버헤드
>lock 닫고 푸는데 시간이 오래걸리기 때문에 이로 인해 성능이 저하될 수 있다. 멀티 쓰레드의 장점을 제대로 살리지 못하는 경우가 생길 수 있다.


# 동기화 방법
  >- https://sujl95.tistory.com/63
  - synchronized 메소드 또는 블록
    - synchronized method는 자기 자신(this)에 대해 lock을 걸고 수행함
    - **공유 객체에 대해서만 동작**하고, primitive에 대해서는 동작하지 않으므로 정상 동작을 항상 점검
    - 관련 Object 메소드: wait(), notify()
  - volatile
    - Java 변수를 Main Memory에 저장하여 공유
  - atomic
    - lock 없이 동기화 처리
    ![](https://images.velog.io/images/san/post/702b2ae7-f88b-4838-845b-e80aecc6f8c8/image.png)
    
# Race Codintion
> 우디: 같은 자원을 서로 다른 스레드나 프로세스가 노리고 있는 상황
> ex) 항공권 예약, 수강신청

# Dead Lock
두 쓰레드가 서로의 lock을 획득하기 위해 대기하고 있는 상태

Process1(ResourceA를 점유한 상태)가 ResourceB를 점유하기를 위해 대기하고 있는 상태
Process2(ResourceA를 점유한 상태)가 ResourceA의 점유하기를 위해 대기하고 있는 상태
![](https://images.velog.io/images/san/post/a6c7ea95-4b87-4fac-8a25-e06383e8b242/image.png)
> Race Condition과는 다른 느낌
> A라는 스레드가 A라는 자원 B라는 스레드가 `점유`하는 B 자원이 있을때, 서로의 자원을 원할때 발생하는 문제?
> 둘 이상의 쓰레드가 락을 획득하기 위해 대기하는데, 해당 락을 잡고있는 쓰레드도 다른 락을 기다리고 있어 block 상태에 놓이는 것
> T1은 T2가 갖고있는 lock2를 기다리고 있고, T2는 T1이 갖고있는 lock1을 대기하는 상황
> ![](https://images.velog.io/images/san/post/aaaf995a-3e0f-4dbf-ac02-2775e9c69680/image.png)

# Dead Lock 원인
> 상호 배제 (Mutual exclusion)
자원은 한 번에 한 프로세스만이 사용할 수 있어야 한다.

>점유 대기 (Hold and wait)
최소한 하나의 자원을 점유하고 있으면서 다른 프로세스에 할당되어 사용하고 있는 자원을 추가로 점유하기 위해 대기하는 프로세스가 있어야 한다.

>비선점 (No preemption)
다른 프로세스에 할당된 자원은 사용이 끝날 때까지 강제로 빼앗을 수 없어야 한다.

>순환 대기 (Circular wait)
프로세스의 집합 {P1,P2…Pn-1, Pn}에서 P1는 P2가 점유한 자원을 대기하고 P2는 P3가 점유한 자원을 대기하고 ... Pn은 P1이 점유한 자원을 요구해야 한다.
이렇게 각 프로세스는 순환적으로 다음 프로세스가 요구하는 자원을 가지고 있다.
