### ISSUE TITLE
[Week11] Enum

### ISSUE THREAD

**Issue by janeljs** [codesquad-study/java#14]
https://github.com/whiteship/live-study/issues/11

**Comment by d-h-k** [comment]
달아줭 병기형

**Comment by pbg0205** [comment]
https://techblog.woowahan.com/2527/

**Comment by pbg0205** [comment]
https://jojoldu.tistory.com/137

**Comment by d-h-k** [comment]
https://velog.io/@dion/%EB%B0%B1%EA%B8%B0%EC%84%A0%EB%8B%98-%EC%98%A8%EB%9D%BC%EC%9D%B8-%EC%8A%A4%ED%84%B0%EB%94%94-11%EC%A3%BC%EC%B0%A8-Enum#enumset%EC%9D%84-%EC%99%9C-%EC%93%B8%EA%B9%8C

**Comment by sanhee** [comment]
> Fail-Safe Iterator는 실제 Collection의 복제본을 작성하고 반복합니다. 
반복자가 작성된 후 수정이 발생해도 사본은 그대로 유지됩니다. 
따라서 이 반복자는 기존 Collection을 수정하더라도 계속 반복됩니다.

https://simuing.tistory.com/entry/JAVA-Fail-Safe-Iterator-vs-Fail-Fast-Iterator

**Comment by janeljs** [comment]
https://www.baeldung.com/java-fail-safe-vs-fail-fast-iterator

**Comment by d-h-k** [comment]
이넘셋을 왜 쓸까
  - 레인지, (쿠퍼 예시코드)
  - 집합관계에서 바라본다 >> 이넘을 집합으로!

**Comment by sanhee** [comment]
valueOf 검증할 때
- Jane 코드 참고

**Comment by janeljs** [comment]
parse, don't validate
```java
public enum Status {
  OPEN(true), 
  CLOSE(false);

  public static Status parse(String statusStr) {
    return Status.valueOf(statusStr.toUpperCase()); 
  }
    
  public Boolean getBoolean() { return this.bool }
}
```
