### ISSUE TITLE
[WEEK12] 애노테이션

### ISSUE THREAD

**Issue by janeljs** [codesquad-study/java#15]
https://github.com/whiteship/live-study/issues/12

**Comment by sanhee** [comment]
## @Transactional

- 어떻게 구성돼있는지
- AOP

**Comment by janeljs** [comment]
### 커스텀 어노테이션
커스텀 어노테이션와 관련된 소스는 java.lang.annotation 패키지에 속해있습니다.
커스텀 어노테이션을 정의하려면 @interface로 선언해주면 됩니다. @는 인터페이스와 어노테이션을 구분하기 위한 기호입니다. interface에 기호를 붙여주는 방식이라서 공백을 넣어 @ interface도 가능하지만, 표준 스타일을 맞추기 위해 공백없이 붙여주는게 좋습니다.
```java
public @interface MyAnnotation {}
```
어노테이션 타입은 컴파일시 항상 java.lang.annotation.Annotation을 슈퍼인터페이스로 상속받아서 인터페이스가 어노테이션 타입임을 나타냅니다. 아래는 컴파일된 class 파일의 내용입니다.
```java
public interface MyAnnotation extends java.lang.annotation.Annotation {}
```
https://hongsii.github.io/2018/12/12/java-annotation/

**Comment by janeljs** [comment]
https://www.geeksforgeeks.org/method-class-getparameterannotations-method-in-java/
