### ISSUE TITLE
[과제] Reflection 정리

### ISSUE THREAD

**Issue by janeljs** [codesquad-study/java#16]

**Comment by sanhee** [comment]
## Reflection

- [https://github.com/tmdgusya/roach-web-server/blob/master/src/main/java/container/annotationProcessor/AutoWiredProcessor.java](https://github.com/tmdgusya/roach-web-server/blob/master/src/main/java/container/annotationProcessor/AutoWiredProcessor.java)
- [https://github.com/tmdgusya/roach-web-server/blob/master/src/main/java/handler/mapping/MappingUrlHandler.java](https://github.com/tmdgusya/roach-web-server/blob/master/src/main/java/handler/mapping/MappingUrlHandler.java)

**Comment by sanhee** [comment]
## @Transactional

- 어떻게 구성돼있는지
- AOP
