### ISSUE TITLE
[Week13] I/O

### ISSUE THREAD

**Issue by pbg0205** [codesquad-study/java#17]
https://github.com/whiteship/live-study/issues/13

**Comment by janeljs** [comment]
### 버퍼
https://github.com/d-h-k/Java_Playground/blob/main/13_FileIO/13_FILE-IO.md#%EB%B2%84%ED%8D%BC-1

**Comment by sanhee** [comment]
동의 추천 서적: 리눅스 커널 내부구조

**Comment by d-h-k** [comment]
https://github.com/d-h-k/Linux-Kernel-Internal
요약하다 만건데

**Comment by janeljs** [comment]
https://en.wikipedia.org/wiki/File_descriptor

**Comment by janeljs** [comment]
https://brunch.co.kr/@myner/47

![image](https://user-images.githubusercontent.com/68000537/124604355-cfab1d00-dea5-11eb-9de9-ece08459e60e.png)

**Comment by janeljs** [comment]
https://bingbingpa.github.io/java/whiteship-live-study-week13/

**Comment by janeljs** [comment]
다시 알아보니까 nio에서 direct buffer와 non-direct buffer 둘 다 사용할 수 있고 direct buffer를 사용할 경우 성능 향상을 기대할 수 있는거였음!!  즉, 아까 말한대로 파일의 크기가 대용량일 때 ㅜnon-direct buffer 말고 direct buffer를 사용하는게 더 좋은건 맞는데  이건 nio 내부에서의 차이였던 것! allocate 메서드를 사용하면 nio에서 non direct 버퍼를 만들 수 있고 allocateDirect 메서드를 사용하면 direct 버퍼를 만들 수 있대!! 생각해보니까 io 는 버퍼안쓰고 nio만 버퍼쓰는데 둘의 성능차이를 버퍼 종류차이로 이해한 것부터가 좀 이상했어

**Comment by janeljs** [comment]
### selector
- https://abn-abn.tistory.com/69

**Comment by janeljs** [comment]
### 멀티쓰레드 환경에서 파일 쓰기
https://codippa.com/how-to-lock-a-file-for-writing-in-java/
