### ISSUE TITLE
[Week14] 제네릭

### ISSUE THREAD

**Issue by sanhee** [codesquad-study/java#19]
https://github.com/whiteship/live-study/issues/14

**Comment by moto6** [comment]
static 멤버의 타입 변수 T를 사용할 수 없음

T는 인스턴스 변수로 간주되기 때문이다.
대입된 타입의 종류에 관계없이 동일한 것이어야 함. 

컴파일타임에 모르고 런타임에만 알수있어서 >>자바의정석 출처

- 참고할만한 자료 블로그 : https://devlog-wjdrbs96.tistory.com/201

**Comment by moto6** [comment]
자바의정석 미스테리 2탄

제네릭 타입의 배열을 생성하는 것도 허용되지 않음. (불가능은 아님)

제네릭 배열 타입의 참조변수를 선언하는 것은 가능

new 연산자 는 컴파일 시점에 타입 T가 무엇인지 정확히 알아야 한다.

new 대신Reflection API의 newInstance()활용

T[] tempArr = new T[itemArr.length]; // 에러, 지네릭 배열 생성불가

**Comment by moto6** [comment]
꺽쇠 `<>` 이거 사라질 위험이 있으니까 특히 신경

**Comment by moto6** [comment]
Type Parameter != Type Arugment

Type Parameter : T in Foo

Type Arugment : Integer in Foo

이렇게 타입 변수자리에 실제로 대입된 타입을 parameterized type 

혼동되므로 주의해랏!


아규면트 : 들어가는 인자갑 func(arg1, arg2)

파라미터 : 

```
int main(int argc, char *[] argv) {
}
```
여기서 유래한거 아닐까??
이

**Comment by moto6** [comment]
```java
class FruitBox<T extends Fruit & Eatable> {...}
```
- 위 상황에서 Fruit클래스랑 Eatable 인터페이스 순서 바뀌어도 괜춘허니??
- 멀티플 바운드하면 >> 3개까지 쓸수 있고
- 클래스 
- 단일상속이니까 인터페이스 두개 

### 출처 : https://docs.oracle.com/javase/tutorial/java/generics/bounded.html

Multiple Bounds
The preceding example illustrates the use of a type parameter with a single bound, but a type parameter can have multiple bounds:

<T extends B1 & B2 & B3>
A type variable with multiple bounds is a subtype of all the types listed in the bound. If one of the bounds is a class, it must be specified first. For example:

Class A { /* ... */ }
interface B { /* ... */ }
interface C { /* ... */ }

class D <T extends A & B & C> { /* ... */ }
If bound A is not specified first, you get a compile-time error:

class D <T extends B & A & C> { /* ... */ }  // compile-time error

**Comment by moto6** [comment]
와일드카드 vs 바운디드 타입의 차이

https://www.youtube.com/watch?v=Vv0PGUxOzq0&t=208s

- 링크 : https://stackoverflow.com/questions/11497020/java-generics-wildcard-extends-number-vs-t-extends-number
-

**Comment by moto6** [comment]
와일드 카드가 필요한 이유

와일드 카드
지네릭 타입이 다른 것으로는 오버로딩 이 성립하지 않아, 메서드 중복 정의로 컴파일 에러가 발생한다.

위와 같은 상황을 해결하기 위해 고안 된것이 와일드 카드 이다.

`void function(<T> parameter)`

**Comment by sanhee** [comment]
![image](https://user-images.githubusercontent.com/73760074/125448677-e93396a3-9571-47b5-9d45-c986ac453f3d.png)


https://devlog-wjdrbs96.tistory.com/201

**Comment by sanhee** [comment]
`public static <T extends Comparable<? super T>> void sort(List<T> list)`

**Comment by moto6** [comment]
# 와일드카드에서 

와일드 카드 (WildCard)
물음표 마크(?)를 와일드 카드로 사용

파라미터, 필드 , 지역변수 혹은 리턴 타입으로 사용

### 제너릭 메소드 호출 시 Type Arugment, 제너릭 클래스에서 인스턴스 생성에는 쓰이지 않는다.
- 리플렉션 사용??
- 포인트 : 인스턴스 생성시 타입아규
- 뉴 키워드는 못쓰고 구체화된 타입으로
- newInstance() :팩토리메서드
```
public static <E> void append(List<E> list) {
    E elem = new E();  // compile-time error
    list.add(elem);
}
```
```
public static <E> void append(List<E> list, Class<E> cls) throws Exception {
    E elem = cls.newInstance();   // OK
    list.add(elem);
}
```

**Comment by sanhee** [comment]
bounded 와일드 카드 사용 기본 원칙

펙스(PECS) : producer-extends, consumer-super

매개변수화 타입 T이 생산자일 때는 extends

매개변수화 타입 T이 소비자일 때는 super

https://github.com/codesquad-study/java/tree/main/Week14/woody

**Comment by sanhee** [comment]
## 공변이 뭐지?..

List와 List는 List의 하위 클래스가 아니기 때문에 아래 예시에서 컴파일 에러 발생
매개변수화 타입은 무공변(invariant)
무공변(invariant) : 상속 관계에 상관없이, 자기 타입만 허용한다. 서로 다른 타입(상속 관계일 수도 있다) Type1과 Type2가 있을 때 List과 List는 서로의 하위 타입도 상위 타입도 아니다.
제너릭 메소드 사용을 위해서는 List<?>를 사용해주어야 한다.

https://github.com/codesquad-study/java/tree/main/Week14/woody

**Comment by moto6** [comment]
- 아래 코드는 컴파일이 될까요?
- from 우디
```
public class Singleton<T> {

    public static T getInstance() {
        if (instance == null)
            instance = new Singleton<T>();

        return instance;
    }

    private static T instance = null;
}
```

**Comment by sanhee** [comment]
브릿지 메소드
![image](https://user-images.githubusercontent.com/73760074/125452688-411fb321-761e-472e-81af-fa2bcb3357ad.png)

**Comment by janeljs** [comment]
### Generic Type으로 인스턴스 생성
- https://blog.asamaru.net/2016/04/11/create-instance-of-generic-type-in-java/
```java
abstract class Gen<T> {
    public T get() {
        try {
            // noinspection unchecked
            Class<T> mClass = (Class<T>) ClassUtils.getReclusiveGenericClass(getClass(), 0);
            if (mClass != null) {
                return mClass.newInstance();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
}

class A {
    public String name = "A!";
}

class GetT extends Gen<A> {
}

public static void main(String[] args) {
    GetT gt = new GetT();
    A a = gt.get();
    System.out.println(a.name);
}
```

**Comment by janeljs** [comment]
- https://intellipaat.com/community/8308/create-instance-of-generic-type-in-java
```java
class SomeContainer<E> {
  private Supplier<E> supplier;
  SomeContainer(Supplier<E> supplier) {
    this.supplier = supplier;
  }

  E createContents() {
    return supplier.get();
  }
}
```
```java
SomeContainer<String> stringContainer = new SomeContainer<>(String::new);
```
