### ISSUE TITLE
[Week15] 람다식

### ISSUE THREAD

**Issue by sanhee** [codesquad-study/java#20]
https://github.com/whiteship/live-study/issues/15

**Comment by d-h-k** [comment]
쉐도잉 개념 잘 모르겠어용..ㅠ

**Comment by janeljs** [comment]
- https://ryan-han.com/post/java/java-lambda/
람다식은 메서드와 동등한 것이 아니라 익명클래스의 객체와 동등하다.
```java
// 람다식
  (int a, int b) -> a > b ? a : b

// 익명클래스의 객체
  new Object()  {
    int max(int a, int b) {
      return a > b ? a : b ;
    }
  }
```
람다식으로 정의된 익명 객체의 메서드를 호출하려면 참조변수가 필요하다.
이 때, 참조변수의 타입은 클래스 또는 인터페이스가 가능한데,
람다식과 동등한 메서드가 정의되어 있는 것이어야 한다.
```java
// 예를 들어 max() 메서드가 정의된 Myfunction 인터페이스 정의
  interface MyFunction  {
    public abstract int max(int a, int b);

// MyFunction 인터페이스를 구현한 익명클래스 객체 생성
  MyFunction f = new MyFunction() {
    public int max (int a, int b);
      return a > b ? a : b;
    }
  }
  int big = f.max(5, 3);  //익명 객체의 메서드 호출

// 위의 익명 객체를 람다식으로 대체
  MyFunction f = (int a, int b) -> a > b ? a : b;
  int big = f.max(5, 3);

```
위 처럼 MyFunction 인터페이스를 구현한 익명 객체를 람다식으로 대체 가능한 이유는 람다식도 실제로는 익명 객체이고, MyFunction 인터페이스를 구현한 익명 객체의 메서드 max()와 람다식의 매개변수의 타입과 개수, 반환값이 일치하기 때문이다.

단, 함수형 인터페이스에는 오직 하나의 추상 메서드만 정의되어 있어야 한다. 그래야 람다식과 인터페이스가 1:1로 연결되기 때문이다. 반면 static 메서드와 default 메서드의 개수에는 제약이 없다.

@FunctionalInterface를 붙이면 컴파일러가 함수형 인터페이스를 올바르게 정의하였는지 확인해준다.

**Comment by sanhee** [comment]
참조투명성

- 함수외부의 값이나 객체의 의존적이지 않기때문에 사이드 이펙트가 없다.
https://github.com/codesquad-study/java/blob/main/Week15/dong/15_Functional_%EA%B0%B1%EC%83%9D.md

**Comment by janeljs** [comment]
https://velog.io/@janeljs/Java-Functional-Programming

### 순수 함수 (Pure function)
- 수학에서는 '상태'라는 개념이 없기 때문에 모든 함수는 함수 외부에 영향을 받지 않고 독립적으로 존재하는데, 이러한 수학의 함수를 프로그래밍 세계로 가져와 만든 모델이 순수함수이다.

특징
- 함수 외부의 값이나 객체에 의존적이지 않기 때문에 참조투명성을 가진다.
- 상태를 변경하지 않기 때문에, 부작용(side-effect)이 없다.
순수함수의 불변성은 다음과 같은 장점을 갖는다.

함수 외부의 상태에 접근하여 이미 메모리에 할당되어 있는 값을 변경하지 않기 때문에 예측하지 못한 상태의 변경을 방지할 수 있다.
참조에 의한 호출을 사용하는 자료형들의 상태 변화를 쉽게 감지할 수 있기 때문에 상태의 변경을 추적하기 쉽다.
함수의 실행이 외부에 영향을 미치지 않기 때문에 스레드 안전(Thread-safe)하고 병렬적인 계산이 가능하다.
데이터가 불변 객체에 저장되어 있다면 복수의 스레드에서 특정한 스레드의 데이터가 변경될 걱정 없이 데이터에 접근하는 것이 가능하다.

**Comment by sanhee** [comment]
![image](https://user-images.githubusercontent.com/73760074/125456509-204a93cd-192a-4080-9363-6fb70c550555.png)

ElementType.Type 은 파라미터도?

**Comment by pbg0205** [comment]
멱등성이 없다.
- 추가만 함
- 이슈 post 100개 요청
  - 데이터베이스에 100개가 쌓임


멱등성이 있음
- put
 - drop을 하고 추가를 함
 - 이슈 post 100개 요청
   - 데이터베이스에 1개 쌓임

**Comment by sanhee** [comment]
`Variable Capture`
다른 언어의 **closure**와 같은 의미

람다식을 사용할 때 외부 변수를 람다식 내부에서 접근할 수 있다.

Closure로 불리는 이유 : 함수의 scope이 확장되서 int a까지 덮어버린다(close over) -> "Closure"

![image](https://user-images.githubusercontent.com/73760074/125459842-1c3ec5e4-a9d1-41a3-9277-dd4e870a0610.png)

**Comment by janeljs** [comment]
클로저 정리했던 것
- https://velog.io/@janeljs/Java-Closure

클로저 MDN
- https://developer.mozilla.org/ko/docs/Web/JavaScript/Closures

**Comment by sanhee** [comment]
## 람다 파트의 파트의 쉐도잉?? 

- 뭔지 모르겠음
- 백기선님 유튜브 출처
https://docs.oracle.com/javase/tutorial/java/javaOO/nested.html#shadowing

**Comment by sanhee** [comment]
effectively final

Functional<> f = (a,b)->{...`enclosing scope 영역`}

**Comment by sanhee** [comment]
https://github.com/codesquad-study/java/tree/main/Week15/woody


![image](https://user-images.githubusercontent.com/73760074/125462078-d8396a1f-4942-48a9-b08e-3ea67a0989a8.png)

`2번` 같은 경우는 타입(클래스)으로 메서드에 접근 한 것
`3번` 같은 경우는 s라는 변수로 메서드에 접근한 것??????
```java
String s = new String(“dummy”)
```

```java
Transaction expensive = new Transaction();
```
expensive라는 변수를 통해서, 메서드에 접근


![image](https://user-images.githubusercontent.com/73760074/125462579-905eda91-8beb-44ff-a3b6-9f49b4295aa2.png)

https://way-be-developer.tistory.com/184
https://docs.oracle.com/javase/tutorial/java/javaOO/methodreferences.html

**Comment by janeljs** [comment]
변수 메서드 참조
- https://way-be-developer.tistory.com/184

**Comment by janeljs** [comment]
생성자(Constructor)도 메소드인가?
- https://javacan.tistory.com/entry/37

**Comment by janeljs** [comment]
invoke dynamic
- https://www.baeldung.com/java-invoke-dynamic
- https://www.notion.so/15-757106032d85452cbc60cf1808d53978

**Comment by sanhee** [comment]
invokedynamic
Java SE7 부터 등장한 새로운 바이트 코드 셋이 invokedynamic

기존에 invoke 시리즈는 4가지만 존재했었습니다.

invokevirtual - instance 메소드를 디스패치 하기 위한 명령어.
invokestatic - static 메소드를 디스패치 하기 위한 명령어.
invokeinterface - 인터페이스를 통해서 method를 디스패치 하기 위한 명령어.
invokespecial - 생성자, 수퍼클래스, private method 등 invoke-virtual이 아닌 메소드들을 디스패치하기 위한 명령어.
이사람은 미쳤어.. https://www.notion.so/15-757106032d85452cbc60cf1808d53978
