### ISSUE TITLE
새로운 스터디로의 방향성

### ISSUE THREAD

**Issue by moto6** [codesquad-study/java#22]
# 스터디 2단계 진화 

## 기 : 이글을 쓴 이유
- 저어... @Jane 선생님께서는 어떤이유에서 스터디 참여 안하시는 방향으로 결정하셨는지는 모르겠습니다만!!!
- 저도 어제 회의하면서 속마음으로는 (아 뭔가 해얄할일이 많아지는 기분인데 부담된다 어쩌지... ;ㅁ;) 요런 생각이 조큼은 있었던거같아용!!
또 오늘 아침에 게더에서 노을이랑 살짝콩 이야기 나눠봤는데, 노을도 지금 벌려놓은일이 많아서 약간은 압박 느끼시는거 같아요

## 승&전 : 제 생각과 진단은
1. 스터디가 사람들 과제 많이 내주고 빡세게 진행하는 "실미도" 컨셉의 스터디로 갈수 있고있고
2. 크게 부담없이 만나지만 스터디 시간만큼은 빡집중하는 "헬스장" 켄섭의 스터로 갈수 있고
    - (물론 식단조절정도의 최소한의 스터디 준비는 할수 있지만요!)
    - 제가 많이는 아니지만.. 대학교 다닐때부터 스터디 지원사업같은거 알뜰하게 챙겨서 스터디그룹 장을 좀 몇번 해볼 기회가 있었는데요...
    -  헬스장같은 스터디에서 >> 잘하고싶은 마음, 조급함, 성과압박 등등이 가미되면(이게 어쩔수 없이 섞이드라구요)  >> 스터디가 "헬스장"에서 "실미도" 로 금방 변하게되고 >> 다들 부담을 느끼게 되고 >> 스터디는 그렇게 사라지는거 같아용
3. 코쿼만큼 열심히 하는 + 기본실력은 되는 + 좋은사람들 모인 스터디 구하기도 만들기도 쉽지 않아요 ㅠㅡㅠ... 이거 330만원짜리(66만원*6) 맥북프로 16인치만큼 귀중한 스터디니 그냥 깨기보다는 Back to the basic 해서  "좀더 가벼운 부담과 주제" 로 혼자 내버려 두면 절대로 하지 않을 공부를 조금씩이라도 같이 계속 해나가면 좋을꺼같아용

## 결1 (주제) : 앞으로 스터디 방향 요런건 어떨까 가볍게 의견한스푼
- "스프링 부트" 프레임워크 학습이라는 큰 주제로 "헬스장" 느낌 나는 스터디 진행하면 좋을꺼같은데용
- 아래 몇가지 스터디 주제& 방향에 대한 영점조절 을 해보면
### 스프링 핵심원리 기본편
- 장점 : 스프링 핵심원리 파악에 좋음, 제인선생님이 편함
- 단점 : 제인선생님이 지루함

### 스프링 MVC 1편&2편
- 장점 : 
- 단점 : 없어보임..?

### 스프링 JPA
- 장점 : 면접장에서 JPA 잘알이라는 컨셉을 보여줄수 있다
- 단점 : 컨셉유지를 위해 나중에 DB 공부도 해야할수 있다
   - 또, 마이바티스 쓰는 회사가면 죽쒀서 개준다(근데 마이바티스 쓰는 회사는 안가는게 커리어에 이로울지도...? 카카오네이버 둘다 전사표준이 JPA라긴 하던데..)

## 결2 (스터디 진행방식)
- 위 세가지가 있겠고, 추가자료로 "토비의스프링", "스프링 레시피" 정도 곁들여서 보면 될꺼같아요
- 그래서 스터디 진행은 주당 부담이 되지 않을 정도의 영한님 강좌에서 "섹션" 단위로 주마다 공부해오면 좋을꺼같아요
- 인간지능 학습을 통해 제가 경험한 >> 인강 && 스터디 준비에 소요되는 학습시간은 아래와 같아요
  - 강의시간 * 1배 = 인강만 듣고 아무고토 안하기
  - 강의시간 * 1.2배 = 인강들으면서 빠르게 빠르게 요약정리 해서 최소한도로 스터디 준비할때 걸리는 시간
  - 강의시간 * 3배 = 인강들으면서 + 실습도 하고 + 요약정리하는데 빡 집중해서 걸리는 시간
  - 강의시간 * ????? = 3배에다가 + 꼬리질문 + 중간중간에 모르는거 찾아보기
-  위 정도 시간 예상하셔서 "유투브 볼 시간" 에 인프런 살짝 들어서 최소한"강의만이라도 다 듣고 오자" 목표로 영한님 커리큘럼 완성시키면 좋을꺼같아요
- 다들 아시겠지만.. 영한님 강의 내용만 다 이해하고 내껄로 만들어도 왠만한 회사에 하꼬 주니어 백엔드 개발자보다는 실력적인 측면에서 더 우월할꺼같아요!

**Comment by sanhee** [comment]
오 동!!! 이슈로 작성해주셨네요, 
제가 스타트를 잘 못 끊는데 감사합니다 👍👍

저도 특별한 준비 없이 스터디 시간에만 집중에서 할 수 있는 형식의 스터디면 부담도 덜 되고, 편하게 참여 할 수 있을 것 같아요.
어떤 주제를 할 지는 차차 고민을 해봐야겠지만요😁

그리고 저는 그룹 스터디를 해본 게 이번이 처음인데 모두들 열정적이고 적극적인 게 너무 좋아서, 가급적이면 꾸준히 함께 했으면 좋겠습니다!!.. 
동처럼 취업 하고서도 이어 갈 수 있다면 가장 베스트!!!!

> (여러분들 덕에 스터디에 대한 디폴트가 너무 높아져 버렸네요 허허)

**Comment by moto6** [comment]
이 어쩔수없이 네이버, 인프런 이런데서 스터디 구하면 발생하는 일 간단히 설명해드리면

1주차 : 1주차니까 살짝은 빡세게 달리지 못하고 다음주에 할일 왕창 만들어서 스터디를 실미도로 만든다
2주차 : 첫 과제라 대충 다들 겉보기엔 다된것처럼 준비는 해온다
3주차 : 과제를 안해온다
4주차 : 어쩔수없는 사정이 생기거나, 누군가가 아프다
5주차 : 아무도 모이지 않는다

**Comment by moto6** [comment]
면접스터디 관련해서는 공부하면서 "이거다" 느낌이 드는 주제들을

[면접질문] IoC 컨테이너에 대해서 설명해 주세요

위 같은 형식으로 질문 이슈로 등록해놓고 꼬리질문에 대한거나 설명들 이슈 댓글로 달아서 놓고, 새로운 질문주제가 떠오르면 다른 이슈 링크 남겨도 되서 나중에 "나무위키" 같은 문서 타고타고 넘어다니는 고런느낌으로 준비하면 어떨까요?? 면접은 평소에 준비해두는거 못참지~

**Comment by sanhee** [comment]
https://github.com/codesquad-2021-study/agora

**Comment by moto6** [comment]
https://www.inflearn.com/course/spring-framework_core#curriculum

**Comment by jihye-woo** [comment]
저번 주에는 확실히 이야기 하다보니 욕심이 계속 생겨서 이것저것 이야기했지만 확실히 다시 생각해보고 다른 분들의 생각도 다시들어보니까 **가볍게 꾸준히 참여할 수 있는 스터디**를 만드는 것도 좋을 것 같네요!

## 스터디 개괄적인 진행 방식
#### 1. 공통 목표를 잡고
   - 공통 목표는 동이 말한대로 `"스프링 부트" 프레임워크 학습이라는 큰 주제`를 잡고가면 좋을 것 같아요
   - 개인마다 스프링을 공부하는 방식이 다를 수도 있고, 강의를 이미 들은 사람도 안들은 사람도 있으니까요!
     (물론 저는 아직 안들ㅇ..ㅡㅁ)
 
#### 2. 스터디에서 만나 공부해온 주제들에 대해 가볍게 이야기
   - 일주일동안 공부한 것들을 입밖으로 내뱉어보는 시간이 되어도 좋을 것 같아요!
   - `발표`보다는 공부했던 내용을 `공유`하고 서로 피드백을 주거나 혹은 배워가는 시간을 가진다!

## 근데.. 어떻게 이야기해야하나?  갑분싸 될 위험이 있다..😂 
   - 스터디에서 구체적인 주제나 가이드를 정해놓지 않게 되면 이야깃거리가 없어지고 그대로 스터디 종료될 수도..ㅠ
       -  "음.. 혹시 다른 하실 이야기없으신가요...?😐 " "흠..." "마무리 할까요 그럼...?"

#### 1.  옵션1 - 주제라도 생각해오자 (가벼움 ⭐️⭐️ ⭐️)
   -  스터디에 참여하기 전에 어떤 이야기를 해보면 좋을 것 같은지 **미리 주제를 생각해오거나 issue로 남기는 것**도 좋을 것 같아요
   - 예를 들면, 우리는 스프링 부트 프레임워크 학습을 공통주제로 선정하면, 이번 주 이슈는 `DI 컨테이너와 빈`으로 등록한 뒤 공부하고 각자의 스타일 대로 공부한 뒤 스터디 시간에 자유롭게 이야기!
   - (+) 내용 정리가 의무는 아니기 때문에 정말 가볍게 참여할 수 있다. 내 공부 스케줄에 집중 가능
   - (-) 자율성에 맡기는 수 밖에 없다, 아무도 이야기 주제에 대해 생각해오지 않는다면 거기서 끗.. 하지만 이 멤버구성이라면 계속 이야기할 수 있을지도.?

#### 2.  옵션2 - 강의를 기반으로 가자  (가벼움 ⭐️⭐️ )
   - 각자 목표치 만큼의 강의를 들어오고 스터디에서 강의에서 배운 내용에 대해 이야기한다.
   - (+) 구체적인 커리큘럼이 있고 이야기할 때 서로 아는 내용이라는 전제를 깔고 이야기할 수 있어서 좋다
   - (-) 근데 오히려 다들 강의를 듣고와서 아는 내용이라 이야깃거리가 없을 수도..?👀
   - (-) 강의를 이미 다 들었거나 호옥시나 듣고싶지 않은 사람이 있을 수도..?(물론 저는 듣고싶어효)

#### 3. 노을이 준 [링크](https://github.com/codesquad-2021-study/agora) 대로 ) (가벼움 ⭐️ ⭐️)
   - 일주일마다 [여기](https://github.com/codesquad-2021-study/agora/pulls?q=is%3Apr+is%3Aclosed) 처럼 각자 공부하고 싶은 주제를 선정해서 일주일동안 공부 및 정리. 그리고 간단하게 공부한 내용을 말해준다
   - 발표는 너무 무거우니까 이번 주에 어떤 공부했고 정리한 내용은 대강 무엇인지만 설명
   - (+) 내가 하고싶은 공부를 하면 되니까 자율성은 보장
   - (-) 학습 내용을 작성해서 남겨야한다는 점에서는 강제성이 사알짝 있다

#### 4. 1과 3 짬뽕 버전 ( 가벼움 ⭐️ ) 
   - 미리 공통 주제를 issue로 가지고 가되, 공통 주제 내에서 세부 주제를 선정해서 각자 공부해오고 간단하게 공부한 내용을 말해준다
   - [참고하면 좋을 스터디 레포](https://github.com/11st-corp/spring-study-sprout)
       - 근데 우리는 가볍게 갈거니까 이렇게 발표자료까진 만들지 말고, [여기](https://github.com/codesquad-2021-study/agora/pulls?q=is%3Apr+is%3Aclosed)처럼까지만..? 물론 그래도 강제성을 띈다는 점에서는 그다지 가볍진 않지만!
   - (+) 공통 주제가 있다는 점
   - (-) 공통 주제에 한해서 내용을 작성해야한다는 강제성이 사알짝 있다

**Comment by moto6** [comment]
공유하고 서로 피드백을 주고받는다 >> 너무 좋네요!!!
