### ISSUE TITLE
[WEEK5] 클래스

### ISSUE THREAD

**Issue by janeljs** [codesquad-study/java#7]
https://github.com/whiteship/live-study/issues/5#issue-739429620

**Comment by sanhee** [comment]
- [[코드라떼] 자바 - Call By Value, 값에 의한 호출](https://www.youtube.com/watch?v=Vd1C3-wHc4Y&feature=youtu.be)

- [[코드라떼] 자바 - 메모리 모델 기초](https://www.youtube.com/watch?v=m9lv_Zt7otk)
