### ISSUE TITLE
[WEEK6] 상속

### ISSUE THREAD

**Issue by janeljs** [codesquad-study/java#8]
https://github.com/whiteship/live-study/issues/6#issue-739430095

**Comment by sanhee** [comment]
상속보다는 Composition
- https://www.youtube.com/watch?v=clbpnp2xYOQ
- https://www.youtube.com/watch?v=YJ4JJsGy8rY

**Comment by sanhee** [comment]
static method와 Override hiding
- https://wedul.site/457
- https://www.whiteship.me/hiding-method/
- https://docs.oracle.com/javase/tutorial/java/IandI/override.html

**Comment by sanhee** [comment]
이펙티브 자바 item 18번: 상속
